// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh6koipZvMfcQeMAyPKyFP37cyYCu9PiI',
    appId: '1:308926208828:web:22b8c39555ad3620039c39',
    messagingSenderId: '308926208828',
    projectId: 'wall-share-e9109',
    authDomain: 'wall-share-e9109.firebaseapp.com',
    storageBucket: 'wall-share-e9109.firebasestorage.app',
    measurementId: 'G-V9LWD5XEWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOkWYjNd3SohD9TqhIp0vcvedTrIFZb5o',
    appId: '1:308926208828:android:6281a1d65444aa25039c39',
    messagingSenderId: '308926208828',
    projectId: 'wall-share-e9109',
    storageBucket: 'wall-share-e9109.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOIiwapPwc_TIkMUwj4QXqsbd9D0wWGlE',
    appId: '1:308926208828:ios:aeb496904944044d039c39',
    messagingSenderId: '308926208828',
    projectId: 'wall-share-e9109',
    storageBucket: 'wall-share-e9109.firebasestorage.app',
    iosBundleId: 'com.example.wallShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh6koipZvMfcQeMAyPKyFP37cyYCu9PiI',
    appId: '1:308926208828:web:185404f9caa1c278039c39',
    messagingSenderId: '308926208828',
    projectId: 'wall-share-e9109',
    authDomain: 'wall-share-e9109.firebaseapp.com',
    storageBucket: 'wall-share-e9109.firebasestorage.app',
    measurementId: 'G-3WPF26LCE7',
  );
}
